# INFO --------------------------------------------------------------------
# Source: https://toptipbio.com/qpcr-multiple-reference-genes/

# Ct stands for the cycle threshold (Ct). Simply, it is the cycle number 
# where the fluorescence generated by the PCR produce is distinguishable 
# from the background noise.

# ∆Ct = Ct (gene of interest) – Ct (housekeeping gene)
# Basically, ∆Ct is the difference in Ct values for your gene of interest 
# and your housekeeping gene for a given sample.

# ∆∆Ct = ∆Ct (treated sample) – ∆Ct (untreated sample)
# Essentially, ∆∆Ct is the difference between the ∆Ct values of the 
# treated/experimental sample and the untreated/control sample.

# 1. Average the Ct values for any technical replicates
# 2. Calculate the ∆Ct for each sample
#     ∆Ct = Ct (gene of interest) – Ct (housekeeping gene)
# 3. Select a calibrator/reference sample(s) to calculate ∆∆Ct
#   a) match samples - only works with matched pairs
#   b) the sample with the highest Ct value
#   c) one of the control samples
#   d) average the Ct values of all controls
#     --> Use the geometric mean if the Ct values are more than ±2 apart:
#           prod(ctrl_ct_values)^(1/length(ctrl_ct_values))
# --> Should be kept consistent for an experiment.
# 4. Calculate ∆∆Ct values for each sample
#     ∆∆Ct = ∆Ct (Sample) – ∆Ct (Control average)
# 5. Calculate the fold gene expression values
#     Fold gene expression = 2^-(∆∆Ct)
# 6. It is always best to log transform the values (2^-∆∆Ct) before 
# undertaking statistical analysis. This is because the untransformed 
# gene expression values will most likely not be normally distributed 
# and heavily skewed, especially in experiments where a strong 
# stimulus is used.

# Import data -------------------------------------------------------------

dat_raw <- read_csv(file_path)


# Check blanks ------------------------------------------------------------

check_blanks(dat_raw)


# Clean data --------------------------------------------------------------

tags <- c('x', 'y', 'z')

dat <- dat_raw %>% 
  get_rid_of_blanks() %>% 
  rename_columns() %>% 
  homogenize_font_case() %>% 
  split_tags(tags)


# Average technical replicates --------------------------------------------
## Compute averages
dat <- dat %>% 
  group_by(tags) %>% 
  summarise(avg_cq = mean(cq),
            sd_cq = sd(cq))

## Warn if SD is too high
if(sd_cq > sd_thresh) warning('Your pipetting skills suck!')


# Calculate relative gene expression --------------------------------------
housek <- 'x'
ctrl_group <- 'y'

rel_gene_expression <- dat %>% 
  mutate(
    dct = calc_dct(housek),
    ctrl_mean_ct = calc_ctrl_mean_ct(ctrl_group),
    ddct = calc_ddct(dct, ctrl_mean_ct),
    fold_change = 2^(ddct))







